# See https://github.com/silverstripe/silverstripe-travis-support for setup details
language: php

sudo: false

addons:
  apt:
    packages:
      - poppler-utils

matrix:
  include:
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3.7
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.7
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3

before_script:
  - composer self-update || true
  - mkdir -p $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - export SS_TIKA_ENDPOINT="http://localhost:9998/"
  - ./.travis/install_tika.sh
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - ($HOME/bin/tika-rest-server &) &> /dev/null
  - vendor/bin/phpunit --verbose textextraction/tests/
