mappings:
  FileTextExtractable: SilverStripe\TextExtraction\Extension\FileTextExtractable
  FileTextCache: SilverStripe\TextExtraction\Cache\FileTextCache
  FileTextCache_Cache: SilverStripe\TextExtraction\Cache\FileTextCache\Cache
  FileTextCache_Database: SilverStripe\TextExtraction\Cache\FileTextCache\Database
  FileTextExtractor: SilverStripe\TextExtraction\Extractor\FileTextExtractor
  FileTextExtractor_Exception: SilverStripe\TextExtraction\Extractor\FileTextExtractor\Exception
  HTMLTextExtractor: SilverStripe\TextExtraction\Extractor\HTMLTextExtractor
  PDFTextExtractor: SilverStripe\TextExtraction\Extractor\PDFTextExtractor
  SolrCellTextExtractor: SilverStripe\TextExtraction\Extractor\SolrCellTextExtractor
  TikaServerTextExtractor: SilverStripe\TextExtraction\Extractor\TikaServerTextExtractor
  TikaTextExtractor: SilverStripe\TextExtraction\Extractor\TikaTextExtractor
  TikaRestClient: SilverStripe\TextExtraction\Rest\TikaRestClient

